/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import controlador.ControladorImpl;
import javax.swing.JOptionPane;
/**
 *
 * @author HeroD
 */
public class V_Tarjeta extends javax.swing.JFrame {

    /**
     * Creates new form V_Tarjeta
     */
    
    ControladorImpl contr = new ControladorImpl();
    Menu menu = new Menu();
    
    public V_Tarjeta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cedula = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        recargo = new javax.swing.JTextField();
        crearT = new javax.swing.JButton();
        recargarT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tarejtas");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tu Tarjeta");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CEDULA:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NOMBRE:");

        cedula.setBackground(new java.awt.Color(255, 255, 255));
        cedula.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cedula.setForeground(new java.awt.Color(0, 0, 0));
        cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaActionPerformed(evt);
            }
        });

        nombre.setBackground(new java.awt.Color(255, 255, 255));
        nombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        nombre.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("RECARGO:");

        recargo.setBackground(new java.awt.Color(255, 255, 255));
        recargo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        recargo.setForeground(new java.awt.Color(0, 0, 0));

        crearT.setBackground(new java.awt.Color(255, 255, 255));
        crearT.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        crearT.setForeground(new java.awt.Color(0, 0, 0));
        crearT.setText("CREAR TARJETA");
        crearT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                crearTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                crearTMouseExited(evt);
            }
        });
        crearT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearTActionPerformed(evt);
            }
        });

        recargarT.setBackground(new java.awt.Color(255, 255, 255));
        recargarT.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        recargarT.setForeground(new java.awt.Color(0, 0, 0));
        recargarT.setText("RECARGAR TARJETA");
        recargarT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                recargarTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                recargarTMouseExited(evt);
            }
        });
        recargarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recargarTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(crearT)
                                .addGap(28, 28, 28)
                                .addComponent(recargarT))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(recargo, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                    .addComponent(nombre)
                                    .addComponent(cedula)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(recargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearT)
                    .addComponent(recargarT))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaActionPerformed

    private void crearTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearTMouseEntered
        crearT.setBackground(new Color(51, 204, 0));
        crearT.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_crearTMouseEntered

    private void recargarTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recargarTMouseEntered
        recargarT.setBackground(new Color(51, 204, 0));
        recargarT.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_recargarTMouseEntered

    private void crearTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearTMouseExited
        crearT.setBackground(new Color(255, 255, 255));
        crearT.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_crearTMouseExited

    private void recargarTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recargarTMouseExited
        recargarT.setBackground(new Color(255, 255, 255));
        recargarT.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_recargarTMouseExited

        public static boolean validarN(String cedula) {
        return cedula.matches("[0-9]*");
    }
    
        public boolean validaciones(){
        
                if (!validarN(cedula.getText()) || cedula.getText().equals("")||nombre.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "DATOS INVALIDOS",
                    "VENTANA MENU", JOptionPane.ERROR_MESSAGE);
            return false;
        }//IF 
         return true;
    }
    
    private void crearTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearTActionPerformed

        if(validaciones() == true){  
        contr.crearTarjeta(cedula.getText(), nombre.getText());
        cedula.setText("");
        nombre.setText("");
        recargo.setText("");
        }//IF
       
    }//GEN-LAST:event_crearTActionPerformed

    private void recargarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recargarTActionPerformed
  
        if(validaciones() == true){  
        contr.recargarTarjeta(cedula.getText(), nombre.getText(),  Integer.parseInt(recargo.getText()));
        cedula.setText("");
        nombre.setText("");
        recargo.setText("");
        }
    }//GEN-LAST:event_recargarTActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_Tarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_Tarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_Tarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_Tarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_Tarjeta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cedula;
    private javax.swing.JButton crearT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombre;
    private javax.swing.JButton recargarT;
    private javax.swing.JTextField recargo;
    // End of variables declaration//GEN-END:variables
}
